### ISSUE TITLE
Add TESTNET instructions

### ISSUE THREAD

**Issue by jidanni** [MyEtherWallet/knowledge-base-v3#44]
Other wallets offer an option to connect to a **testnet** to ensure all is running smoothly before risking any *real* money. Although users can find e.g., https://github.com/kvhnuke/etherwallet/issues/61 but [searches](https://www.google.com/search?q=myetherwallet+testnet) don't find much more.

Also please be sure the procedures for making Testnet wallets can be followed [offline](https://myetherwallet.github.io/knowledge-base/offline/running-myetherwallet-locally.html).

**Comment by jidanni** [comment]
Also on https://myetherwallet.github.io/knowledge-base/getting-started/myetherwallet-help-and-quicktips.html tell users to first try TESTNET transactions before attempting:
> 29. For new accounts, especially cold storage, send small amount in & out

> 51. Send a test transaction first & make sure it arrives at intended destination before sending all the ETH

**Comment by JVS-PCS** [comment]
**Hi Jidanni,  could you explain step by step how a novice** like me who is untrained in your field can go to the Block where a SEND is in limbo so to speak because the Receiving Exchange discontinued the ETH wallet.
I know how to us the TX Hash to find my ETH tokens but how do you redirect without violating rules.  Can I place a new address for the Tokens to be returned to the wallet they came from on Coinbase? Please don't send me to Github or give me a one sentence answer that I will not be able to comprehend. If I were 8 yrs old [I am 68 yrs old] how would you tell someone how to retrieve their tokens?  Or are they lost forever case closed no one Gives Rats A** that an investor loses their money.  If I have to correct this myself I need detailed instructions and even at that if it works you will be rewarded.  By reading these sites I am now aware this happens everyday but there must be an equitable solution for Block Chain Evolution to mend itself for all components to run harmoniously for the well being of a new economy trying to be BORN.  Do you understand what I am trying to say?  Security must be more than preventing theft or fraud it must also include making the investors WHOLE[redeeming all assets to the right owner]  Without this element the whole industry will eventually FAIL!  Don't you agree?  Yours for a better future for all nations in the new global economy.    -John V Saputo jvs3@comcast.net   
PS at your work I deleted all of my person details and resent you the file dropping in the email off clipboard.  Thank I know you have my best interest at #  @heart.****

**Comment by JVS-PCS** [comment]
** @ATTN: Jidanni**
By the way regarding my case,  I do have a TREZOR but the basic model redirects you to MEW as the wallet to hold your ETH.  So another option would to be redirecting my 1.9 back to TREZOR and into my MEW wallet?    Thank you for your patience with me,
John V Saputo

**Comment by jidanni** [comment]
@JVS-PCS Rest assured that you are way ahead of me (57). I haven't even got past using the site comfortably / confidently [locally](https://myetherwallet.github.io/knowledge-base/offline/running-myetherwallet-locally.html) let alone online. I think you might have better luck in getting through to staff than I have too.

**Comment by JVS-PCS** [comment]
Dan thanks for the reply but again I don’t have private keys only proof of the transaction because Coinbase is a multi-signature wallet.
When I go to one of these links I don’t have a clue as what I am to do for “Block Geeks” and I say than with affection, know what to do it is their business to know.
I am not trained in all of this lingo.  But I do know that this system will fail it too many people who are honest start losing thousands and thousands of dollars dut to technical mishapes and protocols that prevent staff from helping investors to be made whole and get their assets to the right owner.

 

John V Saputo

 

John V Saputo

**Comment by jidanni** [comment]
Duplicate of #52.
